<?php
/**
 * @file
 * Drupal needs this blank file.
 */

/**
 * Implements hook_menu().
 */
function departments_menu() {

  $items = array();
  // Staff view of items for adminstration purposes.
  $items['departments.xml'] = array(
    'title' => 'Departments',
    'page callback' => '_department_list_json',
    'access arguments' => array('view departments'),
  );
  return $items;
}

/**
 * Implements hook_permission().
 */
function departments_permission() {
  return array(
    'view departments' => array(
      'title' => t('View Departments JSON'),
    ),
  );
}

/**
 * Creates list of departments in JSON format
 */
function _department_list_json() {
  $department_query = new EntityFieldQuery();
  $department_query->entityCondition('entity_type', 'taxonomy_term')
  ->entityCondition('bundle', 'library_departments')
  ->propertyOrderBy('name', 'ASC');
  $departments_result = $department_query->execute();

  $departments = array();
  foreach ($departments_result['taxonomy_term'] as $department) {
    $department_term = taxonomy_term_load($department->tid);
    $department_info = array(
      'name' => $department_term->name,
      'location' => $department_term->field_department_location['und'][0]['safe_value'],
      'phone' => $department_term->field_department_phone['und'][0]['safe_value'],
      'fax' => $department_term->field_department_fax['und'][0]['safe_value'],
      'email' => $department_term->field_department_email['und'][0]['safe_value'],
      'website' => $department_term->field_department_website['und'][0]['safe_value'],
      'members' => array(),
      'department_heads' => array(),
    );

    $member_query = new EntityFieldQuery();
    $member_query->entityCondition('entity_type', 'user')
    ->fieldCondition('field_library_department', 'tid', $department->tid, '=')
    ->fieldOrderBy('field_last_name', 'value', 'ASC');
    $member_result = $member_query->execute();

    $members = array();
    foreach ($member_result['user'] as $uid => $member) {
      $member_user = user_load($uid);
      $member_info = array(
        'first_name' => $member_user->field_first_name['und']['0']['safe_value'],
        'last_name' => $member_user->field_last_name['und']['0']['safe_value'],
        'position' => $member_user->field_position_title['und']['0']['safe_value'],
        'phone' => $member_user->field_phone_number['und']['0']['safe_value'],
        'on_leave' => $member_user->field_on_leave['und']['0']['value'],
        'email' => $member_user->mail,
      );

      $members[] = $member_info;
    }

    $department_info['members'] = $members;

    $dept_head_query = new EntityFieldQuery();
    $dept_head_query->entityCondition('entity_type', 'user')
    ->fieldCondition('field_library_department_head', 'tid', $department->tid, '=')
    ->fieldOrderBy('field_last_name', 'value', 'ASC');
    $dept_head_result = $dept_head_query->execute();

    $dept_heads = array();
    foreach ($dept_head_result['user'] as $uid => $dept_head) {
      $dept_head_user = user_load($uid);
      $dept_head_info = array(
        'first_name' => $dept_head_user->field_first_name['und']['0']['safe_value'],
        'last_name' => $dept_head_user->field_last_name['und']['0']['safe_value'],
        'position' => $dept_head_user->field_position_title['und']['0']['safe_value'],
        'phone' => $dept_head_user->field_phone_number['und']['0']['safe_value'],
        'email' => $dept_head_user->mail,
      );

      $dept_heads[] = $dept_head_info;
    }

    $department_info['department_heads'] = $dept_heads;

    $departments[] = $department_info;
  }

  print json_encode($departments);

  return;
}
